
-- ESQUEMA DE BASE DE DATOS REFACTORIZADO - MYDAILY
-- ADVERTENCIA: Este script ELIMINARÁ las tablas antiguas para recrearlas limpias.
-- Si tienes datos importantes, haz un backup antes de ejecutarlo.

DROP TABLE IF EXISTS public.actividades CASCADE;
DROP TABLE IF EXISTS public.agenda CASCADE;
DROP TABLE IF EXISTS public.calendario CASCADE;
DROP TABLE IF EXISTS public.categorias CASCADE;
DROP TABLE IF EXISTS public.configuraciones CASCADE;
DROP TABLE IF EXISTS public.configuraciones_usuario CASCADE; -- Tabla vieja
DROP TABLE IF EXISTS public.evento CASCADE; -- Tabla vieja
DROP TABLE IF EXISTS public.habitos CASCADE;
DROP TABLE IF EXISTS public.listas CASCADE; -- Tabla vieja
DROP TABLE IF EXISTS public.notas CASCADE;
DROP TABLE IF EXISTS public.recurrencia CASCADE; -- Tabla vieja
DROP TABLE IF EXISTS public.tarea CASCADE; -- Tabla vieja
DROP TABLE IF EXISTS public.usuarios CASCADE;

-- 1. TABLA USUARIOS (Nueva)
-- Centraliza la información del perfil público y configuraciones principales.
-- Relación 1:1 con auth.users de Supabase.
CREATE TABLE public.usuarios (
  id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  username text,
  nombre text,
  apellido text,
  fecha_nacimiento date,
  genero text,
  avatar text DEFAULT 'user-circle',
  tema text DEFAULT 'default',
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT usuarios_pkey PRIMARY KEY (id)
);

-- 2. TABLA CONFIGURACIONES (Normalizada y en Español)
-- Se eliminaron las columnas duplicadas en inglés.
-- Se renombraron columnas para mantener consistencia en Español.
CREATE TABLE public.configuraciones (
  id_config integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  user_id uuid NOT NULL REFERENCES public.usuarios(id) ON DELETE CASCADE,
  
  -- Preferencias de Notificación
  notificaciones_email boolean DEFAULT true,
  notificaciones_push boolean DEFAULT true,
  recordatorios_habitos boolean DEFAULT true, -- Antes habit_reminders
  recordatorios_eventos boolean DEFAULT true, -- Antes event_reminders
  
  -- Preferencias de Uso
  hora_inicio_dia time without time zone DEFAULT '06:00:00', -- Antes hora_inicio / day_start
  meta_habitos_diaria integer DEFAULT 3, -- Antes meta_habitos / daily_goal
  atajos_teclado boolean DEFAULT false, -- Antes keyboard_shortcuts
  
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT configuraciones_pkey PRIMARY KEY (id_config),
  CONSTRAINT configuraciones_user_unique UNIQUE (user_id) -- Asegura una config por usuario
);

-- 3. TABLA NOTAS
CREATE TABLE public.notas (
  id_notas integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  nom character varying NOT NULL, -- Título
  cont text NOT NULL, -- Contenido
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  imagen text,
  estado_animo character varying DEFAULT 'sun',
  favorita boolean DEFAULT false,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT notas_pkey PRIMARY KEY (id_notas)
);

-- 4. TABLA HABITOS
CREATE TABLE public.habitos (
  id_hab integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  nom character varying NOT NULL,
  descr text,
  hora time without time zone NOT NULL,
  prior integer NOT NULL DEFAULT 1,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  racha integer DEFAULT 0,
  progreso_semanal integer DEFAULT 0,
  completado_hoy boolean DEFAULT false,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT habitos_pkey PRIMARY KEY (id_hab)
);

-- 5. TABLA CATEGORIAS (Para Calendario y Actividades)
CREATE TABLE public.categorias (
  id_cat integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  nombre character varying NOT NULL,
  CONSTRAINT categorias_pkey PRIMARY KEY (id_cat)
);

-- 6. TABLA CALENDARIO (Eventos Principales)
CREATE TABLE public.calendario (
  id_cal integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  nom character varying NOT NULL,
  descr text,
  fecha date NOT NULL,
  lugar character varying,
  prior integer NOT NULL DEFAULT 1,
  id_cat integer REFERENCES public.categorias(id_cat),
  id_recur integer, -- Referencia a tabla recurrencia si existe, o simplificar
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT calendario_pkey PRIMARY KEY (id_cal)
);

-- 7. TABLA AGENDA (Detalle de horas para eventos del calendario)
CREATE TABLE public.agenda (
  id_ag integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  id_cal integer NOT NULL REFERENCES public.calendario(id_cal) ON DELETE CASCADE,
  hora_i time without time zone NOT NULL,
  hora_f time without time zone NOT NULL,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT agenda_pkey PRIMARY KEY (id_ag)
);

-- 8. TABLA ACTIVIDADES (To-Do List / Tareas)
CREATE TABLE public.actividades (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  titulo character varying NOT NULL,
  descripcion text,
  fecha date,
  hora time without time zone,
  prioridad character varying, -- 'low', 'medium', 'high'
  categoria character varying,
  completada boolean DEFAULT false,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT actividades_pkey PRIMARY KEY (id)
);

-- NOTA SOBRE TABLAS ELIMINADAS/CONSOLIDADAS:
-- 1. 'evento': Parecía redundante con 'calendario', se ha unificado lógica en 'calendario'.
-- 2. 'recurrencia': Se mantiene referencia en calendario pero se puede crear tabla si es compleja.
-- 3. 'tarea' y 'listas': Parecían duplicadas con 'actividades', se priorizó 'actividades' que es la usada en la APP.
